class Sticker(object)

  
STICKERS = (
    "CAACAgUAAxkBAAFIRQphKQbckc1uXuohdouJ-Uvbwh4gPQAC8QEAAl3yWFfRiO9T02a9dCAE",
    "CAACAgIAAxkBAAFIRRBhKQcXSGLozxhkvFVKswUj-LHl4QAC5QADVp29CggLFmSVBdGKIAQ"
    
)
